insert into author(name) values('kim');
insert into author(name) values('lee');
insert into author(name) values('샘플저자');

insert into book(title, author_id) values('샘플도서1', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서2', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서3', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서4', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서5', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서6', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서7', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서8', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서9', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서10', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서11', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서12', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서13', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서14', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서15', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서16', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서17', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서18', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서19', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서20', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서21', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서22', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서23', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서24', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서25', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서26', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서27', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서28', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서29', (select id from author order by random() limit 1));
insert into book(title, author_id) values('샘플도서30', (select id from author order by random() limit 1));